name: Update Daily Menus

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 06:00 UTC (adjust if needed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 deep-translator

    - name: Run the script
      run: python daily_menus.py

    - name: Commit and push changes
      run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'
        git add index.html
        git commit -m "Auto-update daily menus" || echo "No changes to commit"
        git push
