name: Update Daily Menus

on:
  schedule:
    - cron: '0 6 * * 1-5'  # Every weekday (Monday-Friday) at 06:00 UTC (9:00 AM Finland time)
  workflow_dispatch:

jobs:
  update-menus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 deep-translator

      - name: Run daily_menus.py
        run: python daily_menus.py

      - name: Commit and push updated index.html
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add index.html
          git commit -m "Auto-update lunch menus" || echo "No changes to commit"
          git push
